[project]
name = "smartcity"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka==2.3.0",
    "pandas>=2.0.0",
    "pyspark==3.5.0",
    "simplejson==3.19.2",
]
